---Table: public.covid_table

DROP TABLE public.covid_table;

CREATE TABLE public.covid_table
(
	date	date,
	county	character varying(100) COLLATE pg_catalog."default",
	state	character varying(100) COLLATE pg_catalog."default",
	fips	character varying(100) COLLATE pg_catalog."default",
	cases	double precision,
	deaths	double precision,
	stay_at_home_announced	character varying(100) COLLATE pg_catalog."default",
	stay_at_home_effective	character varying(100) COLLATE pg_catalog."default",
	lat	double precision,
	lon	double precision,
	total_population double precision,
	area_sqmi	double precision,
	population_density_per_sqmi	double precision,
	num_deaths	double precision,
	years_of_potential_life_lost_rate	double precision,
	percent_fair_or_poor_health	double precision,
	average_number_of_physically_unhealthy_days	double precision,
	average_number_of_mentally_unhealthy_days	double precision,
	percent_low_birthweight	double precision,
	percent_smokers	double precision,
	percent_adults_with_obesity	double precision,
	food_environment_index	double precision,
	percent_physically_inactive	double precision,
	percent_with_access_to_exercise_opportunities	double precision,
	percent_excessive_drinking	double precision,
	num_alcohol_impaired_driving_deaths	double precision,
	num_driving_deaths	double precision,
	percent_driving_deaths_with_alcohol_involvement	double precision,
	num_chlamydia_cases	double precision,
	chlamydia_rate	double precision,
	teen_birth_rate	double precision,
	num_uninsured	double precision,
	percent_uninsured	double precision,
	num_primary_care_physicians	double precision,
	primary_care_physicians_rate	double precision,
	num_dentists	double precision,
	dentist_rate	double precision,
	num_mental_health_providers	double precision,
	mental_health_provider_rate	double precision,
	preventable_hospitalization_rate	double precision,
	percent_with_annual_mammogram	double precision,
	percent_vaccinated	double precision,
	high_school_graduation_rate	double precision,
	num_some_college	double precision,
	population	double precision,
	percent_some_college	double precision,
	num_unemployed_CHR	double precision,
	labor_force	double precision,
	percent_unemployed_CHR	double precision,
	percent_children_in_poverty	double precision,
	eightieth_percentile_income	double precision,
	twentieth_percentile_income	double precision,
	income_ratio	double precision,
	num_single_parent_households_CHR	double precision,
	num_households_CHR	double precision,
	percent_single_parent_households_CHR	double precision,
	num_associations	double precision,
	social_association_rate	double precision,
	annual_average_violent_crimes	double precision,
	violent_crime_rate	double precision,
	num_injury_deaths	double precision,
	injury_death_rate	double precision,
	average_daily_pm2_5	double precision,
	presence_of_water_violation	character varying(100) COLLATE pg_catalog."default",
	percent_severe_housing_problems	double precision,
	severe_housing_cost_burden	double precision,
	overcrowding	double precision,
	inadequate_facilities	double precision,
	percent_drive_alone_to_work	double precision,
	num_workers_who_drive_alone	double precision,
	percent_long_commute_drives_alone	double precision,
	life_expectancy	double precision,
	num_deaths_2	double precision,
	age_adjusted_death_rate	double precision,
	num_deaths_3	double precision,
	child_mortality_rate	double precision,
	num_deaths_4	double precision,
	infant_mortality_rate	double precision,
	percent_frequent_physical_distress	double precision,
	percent_frequent_mental_distress	double precision,
	percent_adults_with_diabetes	double precision,
	num_hiv_cases	double precision,
	hiv_prevalence_rate	double precision,
	num_food_insecure	double precision,
	percent_food_insecure	double precision,
	num_limited_access	double precision,
	percent_limited_access_to_healthy_foods	double precision,
	num_drug_overdose_deaths	double precision,
	drug_overdose_mortality_rate	double precision,
	num_motor_vehicle_deaths	double precision,
	motor_vehicle_mortality_rate	double precision,
	percent_insufficient_sleep	double precision,
	num_uninsured_2	double precision,
	percent_uninsured_2	double precision,
	num_uninsured_3	double precision,
	percent_uninsured_3	double precision,
	other_primary_care_provider_rate	double precision,
	percent_disconnected_youth	double precision,
	average_grade_performance	double precision,
	average_grade_performance_2	double precision,
	median_household_income	double precision,
	percent_enrolled_in_free_or_reduced_lunch	double precision,
	segregation_index	double precision,
	segregation_index_2	double precision,
	homicide_rate	double precision,
	num_deaths_5	double precision,
	suicide_rate_age_adjusted	double precision,
	num_firearm_fatalities	double precision,
	firearm_fatalities_rate	double precision,
	juvenile_arrest_rate	double precision,
	average_traffic_volume_per_meter_of_major_roadways	double precision,
	num_homeowners	double precision,
	percent_homeowners	double precision,
	num_households_with_severe_cost_burden	double precision,
	percent_severe_housing_cost_burden	double precision,
	population_2	double precision,
	percent_less_than_18_years_of_age	double precision,
	percent_65_and_over	double precision,
	num_black	double precision,
	percent_black	double precision,
	num_american_indian_alaska_native	double precision,
	percent_american_indian_alaska_native	double precision,
	num_asian	double precision,
	percent_asian	double precision,
	num_native_hawaiian_other_pacific_islander	double precision,
	percent_native_hawaiian_other_pacific_islander	double precision,
	num_hispanic	double precision,
	percent_hispanic	double precision,
	num_non_hispanic_white	double precision,
	percent_non_hispanic_white	double precision,
	num_not_proficient_in_english	double precision,
	percent_not_proficient_in_english	double precision,
	percent_female	double precision,
	num_rural	double precision,
	percent_rural	double precision,
	num_housing_units	double precision,
	num_households_CDC	double precision,
	num_below_poverty	double precision,
	num_unemployed_CDC	double precision,
	per_capita_income	double precision,
	num_no_highschool_diploma	double precision,
	num_age_65_and_older	double precision,
	num_age_17_and_younger	double precision,
	num_disabled	double precision,
	num_single_parent_households_CDC	double precision,
	num_minorities	double precision,
	num_limited_english_abilities	double precision,
	num_multi_unit_housing	double precision,
	num_mobile_homes	double precision,
	num_overcrowding	double precision,
	num_households_with_no_vehicle	double precision,
	num_institutionalized_in_group_quarters	double precision,
	percent_below_poverty	double precision,
	percent_unemployed_CDC	double precision,
	percent_no_highschool_diploma	double precision,
	percent_age_65_and_older	double precision,
	percent_age_17_and_younger	double precision,
	percent_disabled	double precision,
	percent_single_parent_households_CDC	double precision,
	percent_minorities	double precision,
	percent_limited_english_abilities	double precision,
	percent_multi_unit_housing	double precision,
	percent_mobile_homes	double precision,
	percent_overcrowding	double precision,
	percent_no_vehicle	double precision,
	percent_institutionalized_in_group_quarters	double precision,
	percentile_rank_below_poverty	double precision,
	percentile_rank_unemployed	double precision,
	percentile_rank_per_capita_income	double precision,
	percentile_rank_no_highschool_diploma	double precision,
	percentile_rank_socioeconomic_theme	double precision,
	percentile_rank_age_65_and_older	double precision,
	percentile_rank_age_17_and_younger	double precision,
	percentile_rank_disabled	double precision,
	percentile_rank_single_parent_households	double precision,
	percentile_rank_household_comp_disability_theme	double precision,
	percentile_rank_minorities	double precision,
	percentile_rank_limited_english_abilities	double precision,
	percentile_rank_minority_status_and_language_theme	double precision,
	percentile_rank_multi_unit_housing	double precision,
	percentile_rank_mobile_homes	double precision,
	percentile_rank_overcrowding	double precision,
	percentile_rank_no_vehicle	double precision,
	percentile_rank_institutionalized_in_group_quarters	double precision,
	percentile_rank_housing_and_transportation	double precision,
	percentile_rank_social_vulnerability	double precision,
	km_to_closest_station	double precision,
	CALL	character varying(100) COLLATE pg_catalog."default",
	ELEV_M	double precision,
	station_id	double precision,
	station_name	character varying(100) COLLATE pg_catalog."default",
	mean_temp	double precision,
	min_temp	double precision,
	max_temp	double precision,
	dewpoint	double precision,
	sea_level_pressure	double precision,
	station_pressure	double precision,
	visibility	double precision,
	wind_speed	double precision,
	max_wind_speed	double precision,
	wind_gust	double precision,
	precipitation	double precision,
	precip_flag	character varying(100) COLLATE pg_catalog."default",
	fog	double precision,
	rain	double precision,
	snow	double precision,
	hail	double precision,
	thunder	double precision,
	tornado	double precision,
	mean_temp_3d_avg	double precision,
	mean_temp_5d_avg	double precision,
	mean_temp_10d_avg	double precision,
	mean_temp_15d_avg	double precision,
	max_temp_3d_avg	double precision,
	max_temp_5d_avg	double precision,
	max_temp_10d_avg	double precision,
	max_temp_15d_avg	double precision,
	min_temp_3d_avg	double precision,
	min_temp_5d_avg	double precision,
	min_temp_10d_avg	double precision,
	min_temp_15d_avg	double precision,
	dewpoint_3d_avg	double precision,
	dewpoint_5d_avg	double precision,
	dewpoint_10d_avg	double precision,
	dewpoint_15d_avg	double precision,
	date_stay_at_home_announced	character varying(100) COLLATE pg_catalog."default",
	date_stay_at_home_effective	character varying(100) COLLATE pg_catalog."default"
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.covid_table
    OWNER to postgres;
	
--copy covid_table FROM 'US_counties_COVID19_health_weather_data.csv' WITH CSV HEADER DELIMITER AS E'\t' NULL 'NA'

SELECT * FROM covid_table

